apiVersion: automation.cloudbees.io/v1alpha1
kind: action
name: mendsca
inputs:
  server-url:
    required: true
  username:
    required: true
  token:
    required: true
  language:
    required: false
runs:
  using: composite
  steps:
    - id: run-orchestrator
      name: mendsca
      uses: docker://registry.saas-dev.beescloud.com/staging/compliance-mendsca:main-f93ade62503987b609f538d6c6cc87b67dbf2c2a
      shell: bash
      env:
        CONFIG_JSON: '{\"metaInfo\":{\"url\":\"${{ inputs.server-url }}\",\"username\":\"${{ inputs.username }}\",\"password\":\"NA\",\"client_secret\":\"${{ inputs.token }}\",\"toolName\":\"mendsca\"},\"orchestratorInfo\":{\"assetType\":\"CODE\",\"assetIdentifier\":\"${{ cloudbees.scm.repositoryUrl }}\",\"profileIdentifier\":\"${{ cloudbees.scm.branch }}\",\"language\":\"${{ inputs.language }}\"},\"metaInformation\":{\"actor\":\"${{ cloudbees.event.head_commit.author.username }}\",\"commit_id\":\"${{ cloudbees.event.head_commit.id }}\",\"tenent_info\":\"NA\",\"scanner_type\":\"SCA\"}}' 
        RUN_ID: ${{ cloudbees.run_id }}
        STEP_ID: ${{ step.internal.id }}
        JOB_ID: ${{ job.id }}
        DNS_URL: ${{ cloudbees.api.url }}
        JWT_TOKEN: ${{ cloudbees.api.token }}
      run: |
        set -x
        echo "RUN ID: ${{ cloudbees.run_id }}"
        echo "Job ID: ${{ job.id }}"
        echo "Step ID: ${{ step.internal.id }}"      
        cd /app/
        /bin/bash -c "java -jar /app/mend-sca-analyzer.jar & while ! nc -z localhost 5001; do sleep 1; done && /app/orchestrator -scanConfig \"${CONFIG_JSON}\" execute-analyser && exit"


       
        
